Fix TypeError: i.then(...).then(...).catch(...).finally is not a function (#696)
* Fix missing return in mergeEvents

* Use .then instead of .finally